### ISSUE TITLE
Source reading all lines on each change

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-connector-file#27]
### Bug description

The source connector is reading all lines on each change.

### Steps to reproduce

1. Run a pipeline with the following config:
```yaml
---
version: 1.0
pipelines:
  pipeline1:
    status: running
    name: pipeline1
    description: 'file source, file destination'
    connectors:
      file-source:
        type: source
        plugin: "builtin:file"
        name: file-source
        settings:
          path: /home/haris/projects/other/conduit-utils/file-source.txt
      file-destination:
        type: destination
        plugin: "builtin:file"
        name: file-destination
        settings:
          path: /home/haris/projects/other/conduit-utils/file-destination.txt
```
2. Write a new line to the source file.
3. Check the destination file

**Expected behavior**: Only the new line appears in the destination file.

**Actual behavior**: All the lines in the source file are added to the destination file.

### Version

{   "version": "v0.4.0-nightly.20221201",   "os": "linux",   "arch": "amd64" }
